# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jérémy Goulet
email: info@jeremygoulet.ca
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: JeremyGoulet
github_username:  jeremygoulet96

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Server Config options
livereload: true     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

# We specify the directory for Jekyll so we can use @imports.
collections:
  downloads:
    output: false
  telechargements:
    output: false
  work:
    output: true
  portfolio:
    output: true

t:
  en:
    work:
      name: "Work"
      url: "/work/"
    downloads:
      name: "Downloads"
      url: "/downloads/"
    about:
      name: "About me"
      url: "/about-me/"
    contact:
      name: "Contact"
      url: "/contact/"
  fr:
    work:
      name: "Portfolio"
      url: "/portfolio/"
    downloads:
      name: "Téléchargements"
      url: "/telechargements/"
    about:
      name: "À propos"
      url: "/a-propos/"
    contact:
      name: "Me contacter"
      url: "/me-contacter/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - src
  - .idea
  - .icon
  - .DS_Store
  - tsconfig.json
  - README.md
