# JEKYLL SERVE
# Dev : bundle exec jekyll serve
# Prod : JEKYLL_ENV=production bundle exec jekyll build

# Site settings
title: "Jérémy Goulet"
author: "Jérémy Goulet"
email: "info@jeremygoulet.ca"
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I’m Jérémy Goulet. I’m a french canadian living in Quebec City studying multimedia.
  I like to design and code things.
descriptionFr: >- # this means to ignore newlines until "baseurl:"
  Bonjour! Je m'appelle Jérémy Goulet et j'étudie actuellement en Techniques d'intégration multimédia à Québec.
  J'aime faire du design et programmer des choses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jeremygoulet.ca"
twitter_username: "JeremyGoulet"
github_username:  "jeremygoulet96"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Server Config options
livereload: true     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

# We specify the directory for Jekyll so we can use @imports.
# No output for Downloads because no articles
collections:
  downloads:
    output: false
  telechargements:
    output: false
  work:
    output: true
  portfolio:
    output: true

local:
  en:
    work:
      name: "Work"
      url: "/work/"
    downloads:
      name: "Downloads"
      url: "/downloads/"
    about:
      name: "About me"
      url: "/about-me/"
    contact:
      name: "Contact"
      url: "/contact/"
  fr:
    work:
      name: "Portfolio"
      url: "/portfolio/"
    downloads:
      name: "Téléchargements"
      url: "/telechargements/"
    about:
      name: "À propos"
      url: "/a-propos/"
    contact:
      name: "Me contacter"
      url: "/me-contacter/"

# Include in processing.
include:
  - "_pages"
  - "_errors"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - src
  - .idea
  - .icon
  - .DS_Store
  - tsconfig.json
  - README.md
  - ssl
  - yarn.lock
